#!/bin/bash
#
# Comprehensive Report Generator
#
# Generates detailed test reports in multiple formats:
# - Markdown (for GitHub/GitLab)
# - HTML (for web viewing)
# - Summary (for console/CI logs)
#
# Usage:
#   ./tests/generate_report.sh [options] <results_file>
#
# Options:
#   --format, -f     Output format: markdown, html, summary (default: markdown)
#   --output, -o     Output file path (default: stdout)
#   --title, -t      Report title
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Source test configuration
source "${SCRIPT_DIR}/test_config.sh"

# Default options
OUTPUT_FORMAT="markdown"
OUTPUT_FILE=""
REPORT_TITLE="OpenCL Image Processing Framework - Test Report"
RESULTS_FILE=""

# =============================================================================
# Parse Arguments
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --format|-f)
            OUTPUT_FORMAT="$2"
            shift 2
            ;;
        --output|-o)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --title|-t)
            REPORT_TITLE="$2"
            shift 2
            ;;
        -*)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
        *)
            RESULTS_FILE="$1"
            shift
            ;;
    esac
done

# =============================================================================
# Helper Functions
# =============================================================================

generate_markdown_report() {
    local json_file="$1"

    cat << EOF
# ${REPORT_TITLE}

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')
**Platform:** $(uname -s) $(uname -r)
**Commit:** $(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "N/A")

---

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | $(jq -r '.summary.total' "$json_file") |
| Passed | $(jq -r '.summary.passed' "$json_file") |
| Failed | $(jq -r '.summary.failed' "$json_file") |
| Skipped | $(jq -r '.summary.skipped' "$json_file") |
| Pass Rate | $(jq -r '.summary.pass_rate' "$json_file")% |

EOF

    # Status badge
    local passed=$(jq -r '.summary.passed' "$json_file")
    local total=$(jq -r '.summary.total' "$json_file")

    if [[ "$passed" == "$total" ]]; then
        echo "**Status:** :white_check_mark: All Tests Passed"
    else
        echo "**Status:** :x: Some Tests Failed"
    fi

    echo ""
    echo "---"
    echo ""
    echo "## Detailed Results"
    echo ""
    echo "### By Algorithm"
    echo ""

    # Group results by algorithm
    for algo in "${ALGORITHMS[@]}"; do
        echo "#### ${algo}"
        echo ""
        echo "| Variant | Status | GPU Time | CPU Time | Speedup |"
        echo "|---------|--------|----------|----------|---------|"

        jq -r --arg algo "$algo" '.tests[] | select(.algorithm == $algo) | "| \(.variant) | \(.status) | \(.gpu_time_ms // "N/A")ms | \(.cpu_time_ms // "N/A")ms | \(.speedup // "N/A")x |"' "$json_file"

        echo ""
    done

    echo "---"
    echo ""
    echo "## Performance Analysis"
    echo ""
    echo "### Top Performers (by GPU Time)"
    echo ""
    echo "| Rank | Test | GPU Time | Speedup |"
    echo "|------|------|----------|---------|"

    jq -r '[.tests[] | select(.status == "PASS" and .gpu_time_ms != null)] | sort_by(.gpu_time_ms) | to_entries | .[:5] | .[] | "| \(.key + 1) | \(.value.id) | \(.value.gpu_time_ms)ms | \(.value.speedup)x |"' "$json_file"

    echo ""

    # Check for failures
    local failures=$(jq -r '[.tests[] | select(.status == "FAIL" or .status == "ERROR")] | length' "$json_file")

    if [[ "$failures" -gt 0 ]]; then
        echo "---"
        echo ""
        echo "## Failures"
        echo ""

        jq -r '.tests[] | select(.status == "FAIL" or .status == "ERROR") | "### \(.id)\n\n**Status:** \(.status)\n"' "$json_file"
    fi

    echo "---"
    echo ""
    echo "## Test Matrix"
    echo ""
    echo "| Algorithm | Variants Tested | Pass/Fail |"
    echo "|-----------|-----------------|-----------|"

    for algo in "${ALGORITHMS[@]}"; do
        local algo_pass=$(jq -r --arg algo "$algo" '[.tests[] | select(.algorithm == $algo and .status == "PASS")] | length' "$json_file")
        local algo_total=$(jq -r --arg algo "$algo" '[.tests[] | select(.algorithm == $algo)] | length' "$json_file")
        echo "| $algo | $algo_total | $algo_pass/$algo_total |"
    done

    echo ""
    echo "---"
    echo ""
    echo "*Report generated by OpenCL Test Framework*"
}

generate_html_report() {
    local json_file="$1"

    local passed=$(jq -r '.summary.passed' "$json_file")
    local failed=$(jq -r '.summary.failed' "$json_file")
    local total=$(jq -r '.summary.total' "$json_file")
    local pass_rate=$(jq -r '.summary.pass_rate' "$json_file")

    cat << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenCL Test Report</title>
    <style>
        :root {
            --pass-color: #28a745;
            --fail-color: #dc3545;
            --warn-color: #ffc107;
            --bg-color: #f8f9fa;
            --card-bg: #ffffff;
            --text-color: #333;
            --border-color: #dee2e6;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }
        .header h1 { font-size: 24px; margin-bottom: 10px; }
        .header .meta { opacity: 0.9; font-size: 14px; }
        .card {
            background: var(--card-bg);
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 20px;
            margin-bottom: 20px;
        }
        .card h2 { color: #495057; margin-bottom: 15px; border-bottom: 2px solid var(--border-color); padding-bottom: 10px; }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
        }
        .stat-box {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            background: var(--bg-color);
        }
        .stat-box .value { font-size: 32px; font-weight: bold; }
        .stat-box .label { font-size: 14px; color: #6c757d; }
        .stat-box.passed .value { color: var(--pass-color); }
        .stat-box.failed .value { color: var(--fail-color); }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid var(--border-color); }
        th { background: var(--bg-color); font-weight: 600; }
        tr:hover { background: #f1f3f4; }
        .status { padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
        .status.pass { background: #d4edda; color: #155724; }
        .status.fail { background: #f8d7da; color: #721c24; }
        .status.error { background: #fff3cd; color: #856404; }
        .progress-bar {
            width: 100%;
            height: 30px;
            background: var(--fail-color);
            border-radius: 15px;
            overflow: hidden;
            margin: 20px 0;
        }
        .progress-bar .fill {
            height: 100%;
            background: var(--pass-color);
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            transition: width 0.5s ease;
        }
        .algo-section { margin-bottom: 20px; }
        .algo-section h3 { color: #495057; margin-bottom: 10px; }
        .chart-container { height: 200px; margin: 20px 0; }
        footer { text-align: center; color: #6c757d; margin-top: 30px; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>OpenCL Image Processing Framework - Test Report</h1>
            <div class="meta">
EOF

    echo "                Generated: $(date '+%Y-%m-%d %H:%M:%S') | Platform: $(uname -s) $(uname -r)"

    cat << EOF
            </div>
        </div>

        <div class="card">
            <h2>Summary</h2>
            <div class="summary-grid">
                <div class="stat-box">
                    <div class="value">$total</div>
                    <div class="label">Total Tests</div>
                </div>
                <div class="stat-box passed">
                    <div class="value">$passed</div>
                    <div class="label">Passed</div>
                </div>
                <div class="stat-box failed">
                    <div class="value">$failed</div>
                    <div class="label">Failed</div>
                </div>
                <div class="stat-box">
                    <div class="value">${pass_rate}%</div>
                    <div class="label">Pass Rate</div>
                </div>
            </div>
            <div class="progress-bar">
                <div class="fill" style="width: ${pass_rate}%">${pass_rate}% Passed</div>
            </div>
        </div>

        <div class="card">
            <h2>Detailed Results</h2>
            <table>
                <thead>
                    <tr>
                        <th>Test ID</th>
                        <th>Algorithm</th>
                        <th>Variant</th>
                        <th>Status</th>
                        <th>GPU Time</th>
                        <th>CPU Time</th>
                        <th>Speedup</th>
                    </tr>
                </thead>
                <tbody>
EOF

    # Generate table rows from JSON
    jq -r '.tests[] | "<tr><td>\(.id)</td><td>\(.algorithm)</td><td>\(.variant)</td><td><span class=\"status \(.status | ascii_downcase)\">\(.status)</span></td><td>\(.gpu_time_ms // "N/A")ms</td><td>\(.cpu_time_ms // "N/A")ms</td><td>\(.speedup // "N/A")x</td></tr>"' "$json_file"

    cat << 'EOF'
                </tbody>
            </table>
        </div>

        <div class="card">
            <h2>Performance Ranking</h2>
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Test</th>
                        <th>GPU Time</th>
                        <th>Speedup</th>
                    </tr>
                </thead>
                <tbody>
EOF

    jq -r '[.tests[] | select(.status == "PASS" and .gpu_time_ms != null)] | sort_by(.gpu_time_ms) | to_entries | .[] | "<tr><td>\(.key + 1)</td><td>\(.value.id)</td><td>\(.value.gpu_time_ms)ms</td><td>\(.value.speedup)x</td></tr>"' "$json_file"

    cat << 'EOF'
                </tbody>
            </table>
        </div>

        <footer>
            <p>Generated by OpenCL Test Framework</p>
        </footer>
    </div>
</body>
</html>
EOF
}

generate_summary_report() {
    local json_file="$1"

    local passed=$(jq -r '.summary.passed' "$json_file")
    local failed=$(jq -r '.summary.failed' "$json_file")
    local total=$(jq -r '.summary.total' "$json_file")
    local pass_rate=$(jq -r '.summary.pass_rate' "$json_file")

    echo "======================================"
    echo "TEST SUMMARY"
    echo "======================================"
    echo "Total:     $total"
    echo "Passed:    $passed"
    echo "Failed:    $failed"
    echo "Pass Rate: ${pass_rate}%"
    echo "======================================"

    if [[ "$failed" -gt 0 ]]; then
        echo ""
        echo "FAILED TESTS:"
        jq -r '.tests[] | select(.status == "FAIL" or .status == "ERROR") | "  - \(.id): \(.status)"' "$json_file"
    fi

    echo ""

    if [[ "$passed" == "$total" ]]; then
        echo "STATUS: ALL TESTS PASSED"
    else
        echo "STATUS: TESTS FAILED"
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    # If no results file provided, look for most recent JSON report
    if [[ -z "$RESULTS_FILE" ]]; then
        RESULTS_FILE=$(ls -t "${PROJECT_ROOT}/tests/reports/"*.json 2>/dev/null | head -1)
        if [[ -z "$RESULTS_FILE" ]]; then
            echo "Error: No results file provided and no JSON reports found in tests/reports/" >&2
            echo "Usage: $0 [options] <results_file.json>" >&2
            exit 1
        fi
    fi

    if [[ ! -f "$RESULTS_FILE" ]]; then
        echo "Error: Results file not found: $RESULTS_FILE" >&2
        exit 1
    fi

    # Generate report based on format
    local output
    case $OUTPUT_FORMAT in
        markdown|md)
            output=$(generate_markdown_report "$RESULTS_FILE")
            ;;
        html)
            output=$(generate_html_report "$RESULTS_FILE")
            ;;
        summary)
            output=$(generate_summary_report "$RESULTS_FILE")
            ;;
        *)
            echo "Error: Unknown format: $OUTPUT_FORMAT" >&2
            echo "Supported formats: markdown, html, summary" >&2
            exit 1
            ;;
    esac

    # Output to file or stdout
    if [[ -n "$OUTPUT_FILE" ]]; then
        echo "$output" > "$OUTPUT_FILE"
        echo "Report saved to: $OUTPUT_FILE" >&2
    else
        echo "$output"
    fi
}

main "$@"
