#include <stddef.h>

#include "op_interface.h"
#include "op_registry.h"
#include "utils/safe_ops.h"

/**
 * @brief Relu reference implementation
 *
 * CPU implementation of relu algorithm.
 * This serves as the ground truth for verifying GPU output.
 *
 * @param[in] params Operation parameters containing:
 *   - input: Input image buffer
 *   - output: Output image buffer
 *   - src_width, src_height: Source dimensions
 *   - dst_width, dst_height: Destination dimensions
 *   - custom_buffers: Optional custom buffers (NULL if none)
 */
void ReluRef(const OpParams* params) {
    int y;
    int x;
    int width;
    int height;
    unsigned char* input;
    unsigned char* output;
    int total_pixels;
    int output_index;

    if (params == NULL) {
        return;
    }

    /* Extract parameters */
    input = params->input;
    output = params->output;
    width = params->src_width;
    height = params->src_height;

    if ((input == NULL) || (output == NULL) || (width <= 0) || (height <= 0)) {
        return;
    }

    /* MISRA-C:2023 Rule 1.3: Check for integer overflow */
    if (!SafeMulInt(width, height, &total_pixels)) {
        return; /* Overflow detected */
    }

    /* TODO: Implement your algorithm here */
    /* Example: Simple copy operation */
    for (y = 0; y < height; y++) {
        for (x = 0; x < width; x++) {
            output_index = y * width + x;

            /* MISRA-C:2023 Rule 18.1: Bounds check before write */
            if (output_index < total_pixels) {
                output[output_index] = input[output_index];
            }
        }
    }
}

/*
 * NOTE: Registration of this algorithm happens in auto_registry.c
 * Auto-generated by scripts/generate_registry.sh which scans for *_ref.c files.
 *
 * Verification is configured via the [verification] section in config/relu.json:
 *   - tolerance: Maximum allowed pixel difference
 *   - error_rate_threshold: Maximum allowed error rate (0.0 - 1.0)
 *   - golden_source: "c_ref" or "file"
 *   - golden_file: Path to golden output file (if golden_source is "file")
 *
 * Kernel arguments are configured via kernel_args in config/relu.json.
 */
