#!/bin/bash
################################################################################
# create_new_algo.sh
# Create new algorithm template for OpenCL framework
#
# Usage:
#   ./scripts/create_new_algo.sh <algorithm_name>
#
# Example:
#   ./scripts/create_new_algo.sh resize
#
# This will create:
# - examples/<algo>/c_ref/<algo>_ref.c (C reference implementation)
# - examples/<algo>/cl/<algo>0.cl (OpenCL kernel)
# - config/<algo>.json (Configuration file)
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 <algorithm_name>"
    echo ""
    echo "Example:"
    echo "  $0 resize"
    echo "  $0 sobel_edge"
    echo ""
    exit 1
fi

# Get algorithm name and convert to lowercase
ALGO_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')

# Validate algorithm name (alphanumeric, underscore, hyphen only)
if ! echo "$ALGO_NAME" | grep -qE '^[a-z0-9_-]+$'; then
    echo -e "${RED}Error: Algorithm name '$ALGO_NAME' contains invalid characters.${NC}"
    echo "Use only letters, numbers, underscores, and hyphens."
    exit 1
fi

# Normalize name for C identifiers (replace hyphens with underscores)
ALGO_NAME_C=$(echo "$ALGO_NAME" | tr '-' '_')
ALGO_NAME_UPPER=$(echo "$ALGO_NAME_C" | tr '[:lower:]' '[:upper:]')

# Convert snake_case to PascalCase (e.g., dilate3x3 -> Dilate3x3)
ALGO_NAME_PASCAL=$(echo "$ALGO_NAME_C" | awk -F'_' '{for(i=1;i<=NF;i++) printf "%s", toupper(substr($i,1,1)) substr($i,2)}')

# Define paths
C_REF_DIR="examples/${ALGO_NAME}/c_ref"
CL_DIR="examples/${ALGO_NAME}/cl"
C_REF_FILE="${C_REF_DIR}/${ALGO_NAME_C}_ref.c"
CL_FILE="${CL_DIR}/${ALGO_NAME_C}0.cl"
CONFIG_FILE="config/${ALGO_NAME}.json"

# Check if files already exist
HAS_ERRORS=0
if [ -f "$C_REF_FILE" ]; then
    echo -e "${RED}Error: Algorithm '$ALGO_NAME' already exists!${NC}"
    echo "File already exists: $C_REF_FILE"
    HAS_ERRORS=1
fi
if [ -f "$CL_FILE" ]; then
    [ $HAS_ERRORS -eq 0 ] && echo -e "${RED}Error: Algorithm '$ALGO_NAME' already exists!${NC}"
    echo "File already exists: $CL_FILE"
    HAS_ERRORS=1
fi
if [ -f "$CONFIG_FILE" ]; then
    [ $HAS_ERRORS -eq 0 ] && echo -e "${RED}Error: Algorithm '$ALGO_NAME' already exists!${NC}"
    echo "File already exists: $CONFIG_FILE"
    HAS_ERRORS=1
fi

if [ $HAS_ERRORS -eq 1 ]; then
    exit 1
fi

# Create directories
echo "Creating algorithm template for: $ALGO_NAME"
echo ""

mkdir -p "$C_REF_DIR"
echo -e "${GREEN}✓${NC} Created directory: $C_REF_DIR"

mkdir -p "$CL_DIR"
echo -e "${GREEN}✓${NC} Created directory: $CL_DIR"

mkdir -p "config"

################################################################################
# Generate C reference implementation
################################################################################
cat > "$C_REF_FILE" << EOF
#include <stddef.h>

#include "op_interface.h"
#include "op_registry.h"
#include "utils/safe_ops.h"

/**
 * @brief ${ALGO_NAME_PASCAL} reference implementation
 *
 * CPU implementation of ${ALGO_NAME} algorithm.
 * This serves as the ground truth for verifying GPU output.
 *
 * @param[in] params Operation parameters containing:
 *   - input: Input image buffer
 *   - output: Output image buffer
 *   - src_width, src_height: Source dimensions
 *   - dst_width, dst_height: Destination dimensions
 *   - custom_buffers: Optional custom buffers (NULL if none)
 */
void ${ALGO_NAME_PASCAL}Ref(const OpParams* params) {
    int y;
    int x;
    int width;
    int height;
    unsigned char* input;
    unsigned char* output;
    int total_pixels;
    int output_index;

    if (params == NULL) {
        return;
    }

    /* Extract parameters */
    input = params->input;
    output = params->output;
    width = params->src_width;
    height = params->src_height;

    if ((input == NULL) || (output == NULL) || (width <= 0) || (height <= 0)) {
        return;
    }

    /* MISRA-C:2023 Rule 1.3: Check for integer overflow */
    if (!SafeMulInt(width, height, &total_pixels)) {
        return; /* Overflow detected */
    }

    /* TODO: Implement your algorithm here */
    /* Example: Simple copy operation */
    for (y = 0; y < height; y++) {
        for (x = 0; x < width; x++) {
            output_index = y * width + x;

            /* MISRA-C:2023 Rule 18.1: Bounds check before write */
            if (output_index < total_pixels) {
                output[output_index] = input[output_index];
            }
        }
    }
}

/*
 * NOTE: Registration of this algorithm happens in auto_registry.c
 * Auto-generated by scripts/generate_registry.sh which scans for *_ref.c files.
 *
 * Verification is configured via the [verification] section in config/${ALGO_NAME}.json:
 *   - tolerance: Maximum allowed pixel difference
 *   - error_rate_threshold: Maximum allowed error rate (0.0 - 1.0)
 *   - golden_source: "c_ref" or "file"
 *   - golden_file: Path to golden output file (if golden_source is "file")
 *
 * Kernel arguments are configured via kernel_args in config/${ALGO_NAME}.json.
 */
EOF

echo -e "${GREEN}✓${NC} Created file: $C_REF_FILE"

################################################################################
# Generate OpenCL kernel
################################################################################
cat > "$CL_FILE" << EOF
/**
 * @file ${ALGO_NAME_C}0.cl
 * @brief ${ALGO_NAME_PASCAL} OpenCL kernel implementation
 *
 * TODO: Add algorithm description here
 *
 * Kernel arguments (must match kernel_args in config/${ALGO_NAME}.json):
 * @param input  Input image buffer
 * @param output Output image buffer
 * @param width  Image width in pixels
 * @param height Image height in pixels
 */

__kernel void ${ALGO_NAME_C}(__global const uchar* input,
                             __global uchar* output,
                             int width,
                             int height) {
    int x = get_global_id(0);
    int y = get_global_id(1);

    /* Boundary check */
    if (x >= width || y >= height) return;

    int index = y * width + x;

    /* TODO: Implement your algorithm here */
    /* Example: Simple copy operation */
    output[index] = input[index];
}
EOF

echo -e "${GREEN}✓${NC} Created file: $CL_FILE"

################################################################################
# Generate configuration file (JSON format)
################################################################################
cat > "$CONFIG_FILE" << EOF
{
    "input": {
        "input_image_id": "${ALGO_NAME}_input"
    },

    "output": {
        "output_image_id": "${ALGO_NAME}_output"
    },

    "verification": {
        "tolerance": 0,
        "error_rate_threshold": 0,
        "golden_source": "c_ref",
        "golden_file": "test_data/${ALGO_NAME}/golden.bin"
    },

    "kernels": {
        "v0": {
            "description": "standard OpenCL",
            "host_type": "standard",
            "kernel_option": "",
            "kernel_file": "examples/${ALGO_NAME}/cl/${ALGO_NAME_C}0.cl",
            "kernel_function": "${ALGO_NAME_C}",
            "work_dim": 2,
            "global_work_size": [1920, 1088],
            "local_work_size": [16, 16],
            "kernel_args": [
                {"i_buffer": ["uchar", "src"]},
                {"o_buffer": ["uchar", "dst"]},
                {"param": ["int", "src_width"]},
                {"param": ["int", "src_height"]}
            ]
        }
    }
}
EOF

echo -e "${GREEN}✓${NC} Created file: $CONFIG_FILE"

################################################################################
# Print success message and next steps
################################################################################
echo ""
echo "======================================================================"
echo "Algorithm template created successfully!"
echo "======================================================================"
echo ""
echo "Created files:"
echo "  - $C_REF_FILE"
echo "  - $CL_FILE"
echo "  - $CONFIG_FILE"
echo ""
echo "Next steps:"
echo ""
echo -e "${YELLOW}1. Add input image entry to config/inputs.json:${NC}"
cat << INPUTS_EXAMPLE
   "${ALGO_NAME}_input": {
       "input": "test_data/${ALGO_NAME}/input.bin",
       "src_width": 1920,
       "src_height": 1080,
       "src_channels": 1,
       "src_stride": "1920 * 1"
   }
INPUTS_EXAMPLE
echo ""
echo -e "${YELLOW}2. Add output image entry to config/outputs.json:${NC}"
cat << OUTPUTS_EXAMPLE
   "${ALGO_NAME}_output": {
       "output": "test_data/${ALGO_NAME}/output.bin",
       "dst_width": 1920,
       "dst_height": 1080,
       "dst_channels": 1,
       "dst_stride": "1920 * 1"
   }
OUTPUTS_EXAMPLE
echo ""
echo "3. Implement the algorithm in: $C_REF_FILE"
echo "4. Implement the OpenCL kernel in: $CL_FILE"
echo "5. Configure kernel_args and verification in: $CONFIG_FILE"
echo "6. Create test data directory: mkdir -p test_data/${ALGO_NAME}/"
echo "7. Generate test input (or create your own input.bin)"
echo "8. Regenerate registry: ./scripts/generate_registry.sh"
echo "9. Rebuild the project: ./scripts/build.sh"
echo "10. Run your algorithm: ./build/opencl_host ${ALGO_NAME} 0"
echo ""
echo "See config/template.json for a complete example with all options."
echo "See docs/ADD_NEW_ALGO.md for detailed implementation guide."
