#!/bin/bash

# Auto-generate algorithm registry by scanning source files
# Finds all *_ref.c files and creates registration code

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
EXAMPLES_DIR="$PROJECT_ROOT/examples"
OUTPUT_FILE="$PROJECT_ROOT/src/core/auto_registry.c"

echo "=== Auto-generating algorithm registry ==="

# Find all algorithm reference files
ALGO_FILES=$(find "$EXAMPLES_DIR" -name "*_ref.c" -type f | sort)

if [ -z "$ALGO_FILES" ]; then
    echo "Error: No algorithm files found (*_ref.c)"
    exit 1
fi

# Start generating the output file
cat > "$OUTPUT_FILE" <<'EOF'
/**
 * @file auto_registry.c
 * @brief Auto-generated algorithm registry
 *
 * This file is automatically generated by scripts/generate_registry.sh
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * The build system scans for all *_ref.c files and automatically
 * registers them here.
 */

#include "op_interface.h"
#include "op_registry.h"

EOF

# Add forward declarations for each algorithm
echo "// Forward declarations" >> "$OUTPUT_FILE"
for file in $ALGO_FILES; do
    # Extract algorithm name (e.g., dilate3x3_ref.c -> dilate3x3)
    basename=$(basename "$file" .c)
    algo_name=${basename%_ref}

    echo "Found algorithm: $algo_name"

    # Convert snake_case to PascalCase (e.g., dilate3x3 -> Dilate3x3)
    pascal_name=$(echo "$algo_name" | awk -F'_' '{for(i=1;i<=NF;i++) printf "%s", toupper(substr($i,1,1)) substr($i,2)}')

    # Add extern declaration for reference implementation only
    # (verification is now config-driven via [verification] section)
    cat >> "$OUTPUT_FILE" <<EOF
extern void ${pascal_name}Ref(const OpParams* params);
EOF
done

# Add algorithm structures
echo "" >> "$OUTPUT_FILE"
echo "// Algorithm structures" >> "$OUTPUT_FILE"
for file in $ALGO_FILES; do
    basename=$(basename "$file" .c)
    algo_name=${basename%_ref}

    # Convert snake_case to PascalCase (e.g., dilate3x3 -> Dilate3x3)
    pascal_name=$(echo "$algo_name" | awk -F'_' '{for(i=1;i<=NF;i++) printf "%s", toupper(substr($i,1,1)) substr($i,2)}')

    # Use PascalCase for display name (e.g., dilate3x3 -> Dilate3x3)
    display_name="$pascal_name"

    # Generate algorithm structure (verify_result removed - now config-driven)
    cat >> "$OUTPUT_FILE" <<EOF
static Algorithm ${algo_name}_algorithm = {
    .name = "$display_name",
    .id = "$algo_name",
    .reference_impl = ${pascal_name}Ref
};

EOF
done

# Add registration function
cat >> "$OUTPUT_FILE" <<'EOF'
/**
 * @brief Auto-register all algorithms
 *
 * Called from main() to register all algorithms.
 * NOTE: Constructor attribute doesn't work reliably with static libraries,
 * so this must be called explicitly from main().
 */
void AutoRegisterAlgorithms(void) {
EOF

for file in $ALGO_FILES; do
    basename=$(basename "$file" .c)
    algo_name=${basename%_ref}

    echo "    RegisterAlgorithm(&${algo_name}_algorithm);" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" <<'EOF'
}
EOF

echo "Generated: $OUTPUT_FILE"
echo "Registered $(echo "$ALGO_FILES" | wc -l | tr -d ' ') algorithms"
